/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quickchatter.ui.view;

import javax.swing.JFrame;
import org.jetbrains.annotations.NotNull;
import quickchatter.ui.TextValue;
import quickchatter.ui.listdata.JListData;
import quickchatter.utilities.Callback;
import quickchatter.utilities.Logger;
import quickchatter.utilities.SimpleCallback;

public class ReconnectFrame extends javax.swing.JFrame implements BaseView.Whole {
    // Callbacks
    public @NotNull SimpleCallback onNavigateBack = SimpleCallback.createDoNothing();
    public @NotNull Callback<Integer> onSelectItem = Callback.createDoNothing();
    public @NotNull Callback<Integer> onClickItem = Callback.createDoNothing();
    public @NotNull Callback<Integer> onDoubleClickItem = Callback.createDoNothing();

    /**
     * Creates new form ReconnectForm
     */
    public ReconnectFrame() {
        initComponents();
        setup();
    }
    
    public void updateClientsListData(JListData<String> data) {
        resetSelectIndex();
        
        pairedClientsList.setModel(data);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        clientsList = new javax.swing.JScrollPane();
        pairedClientsList = new javax.swing.JList<>();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLabel.setText("Previously paired");

        pairedClientsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pairedClientsListMouseClicked(evt);
            }
        });
        clientsList.setViewportView(pairedClientsList);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(clientsList)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                        .addGap(63, 63, 63)
                        .addComponent(backButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(backButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientsList, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        onNavigateBack.perform();
    }//GEN-LAST:event_backButtonActionPerformed

    private void pairedClientsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pairedClientsListMouseClicked
        int selectedIndex = pairedClientsList.getSelectedIndex();
        
        if (_selectedIndex != selectedIndex) {
            onSelectItem(selectedIndex);
        }
        
        // Click event
        if (evt.getClickCount() == 1)
        {
            onClickItem(_selectedIndex);
        }
        
        // Double click event
        if (evt.getClickCount() == 2)
        {
            onDoubleClickItem(_selectedIndex);
        }
    }//GEN-LAST:event_pairedClientsListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReconnectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReconnectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReconnectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReconnectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReconnectFrame().setVisible(true);
            }
        });
    }
    
    private void setup() {
        ViewUtilities.setAppIconForFrame(this);
        
        this.setTitle(TextValue.getText(TextValue.ScreenReconnect_Title));
    }
    
    // # BaseView
    
    @Override
    public void onStart() {
        setVisible(true);
    }

    @Override
    public void onSuspended() {
        
    }

    @Override
    public void onResume() {
        
    }

    @Override
    public void onTerminate() {
        setVisible(false);
    }
    
    @Override
    public void navigateBack() {
        
    }

    @Override
    public void reloadData() {
        
    }
    
    @Override
    public @NotNull JFrame asFrame() {
        return this;
    }
    
    @Override
    public void open() {
        setVisible(true);
    }
    
    // # Private
    
    private void resetSelectIndex() {
        _selectedIndex = -1;
    }
    
    private void onSelectItem(int index) {
        _selectedIndex = index;
        
        onSelectItem.perform(index);
    }
    
    private void onClickItem(int index) {
        _selectedIndex = index;
        
        onClickItem.perform(index);
    }
    
    private void onDoubleClickItem(int index) {
        _selectedIndex = index;
        
        onDoubleClickItem.perform(index);
    }
    
    private int _selectedIndex = -1;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JScrollPane clientsList;
    private javax.swing.JList<String> pairedClientsList;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
